extern const GeoLayout dummy_area_1_geo[];
extern const GeoLayout dummy_area_1[];
extern const Collision dummy_area_1_collision[];
extern const MacroObject dummy_area_1_macro_objs[];
extern Lights1 dummy_dl_f3dlite_material_lights;
extern Vtx dummy_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx dummy_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_dummy_dl_f3dlite_material[];
extern Gfx dummy_dl_Cube_mesh_layer_1[];
extern Gfx dummy_dl_material_revert_render_settings[];
